"""Initial migration.

Revision ID: 250e07940250
Revises: 
Create Date: 2024-06-22 19:08:10.577690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '250e07940250'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filed_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('bank_address', sa.String(length=200), nullable=False),
    sa.Column('suspicious_activity_code', sa.String(length=50), nullable=False),
    sa.Column('agent_narrative', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('identification_number', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('email_address', sa.String(length=100), nullable=False),
    sa.Column('sar_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sar_id'], ['sar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entity')
    op.drop_table('sar')
    # ### end Alembic commands ###
